### ISSUE TITLE
`ConcurrentModificationException` from `OSXSystemProperties`'s `fireChangeEvent`

### ISSUE THREAD

**Issue by karlvr** [violetlib/vaqua#32]
There are some listeners to the change event in `OSXSystemProperties` that add or remove listeners when they receive the event. My code doesn't directly access `OSXSystemProperties`, but maybe it's some listeners on appearance events in my code... either way, there's a `ConcurrentModifcationException` in `OSXSystemProperties`'s `fireChangeEvent` method if this happens:

```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.base/java.util.ArrayList$Itr.next(Unknown Source)
	at VAqua@11.1-SNAPSHOT/org.violetlib.aqua.OSXSystemProperties$1.run(OSXSystemProperties.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by cbfiddle** [comment]
The code doesn't look like this anymore.
