### ISSUE TITLE
Build problem with VBuilder due to missing commons-codec

### ISSUE THREAD

**Issue by karlvr** [violetlib/vaqua#44]
I have installed the uber jar into `~/.ant/lib`:

```
-rw-r--r--@ 1 karlvr  staff   224277 Nov  2  2006 ant-contrib-1.0b3.jar
-rw-r--r--@ 1 karlvr  staff  4257345 Sep 26  2020 maven-resolver-ant-tasks-1.2.1-uber.jar
-rw-r--r--@ 1 karlvr  staff  4508026 Jun  8 10:55 vbuilder-ant-uber-3.jar
```

Then when I run `ant` in the `./release` dir I get this error:

```
  [resolve] Downloading https://maven-central-asia.storage-download.googleapis.com/maven2/org/violetlib/vappearances/4/vappearances-4.pom
  [resolve] Downloading https://maven.cactuslab.com/releases/org/violetlib/vappearances/4/vappearances-4.pom

BUILD FAILED
/Users/karlvr/Development/VAqua/release/build.xml:157: java.lang.NoClassDefFoundError: org/apache/commons/codec/binary/Base64
        at org.apache.http.impl.auth.BasicScheme.authenticate(BasicScheme.java:166)
        at org.apache.http.impl.auth.HttpAuthenticator.doAuth(HttpAuthenticator.java:233)
        at org.apache.http.impl.auth.HttpAuthenticator.generateAuthResponse(HttpAuthenticator.java:198)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:262)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:442)
        at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:392)
        at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:64)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:482)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:414)
...
Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.binary.Base64
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 52 more
```

It looks to me like it's trying to download poms for violetlib dependencies and missing the commons-codec library.

Downloading and installing `commons-codec-1.17.0.jar` into `~/.ant/lib` fixes that particular build issue.

**Comment by cbfiddle** [comment]
I’m using maven-resolver-ant-tasks-1.5.0-uber.jar, perhaps that makes a difference.

**Comment by karlvr** [comment]
@cbfiddle I upgraded to 1.5.1 and it has the same issue. I think I might be a bit early in using the new build anyway, as I noticed it's not all released yet (which is why it fails to download the violetlib dependencies, once I get past the codec issue). I'm curious about your JNU step... have you written about this anywhere? I worked around the JNF thing by bundling it with my app and hard-coding the framework path in the build of vappearances and jnr. Not exactly pleasant.

**Comment by cbfiddle** [comment]
Make sure you have the uber JAR of the resolver. Mine contains commons-codec.

**Comment by karlvr** [comment]
@cbfiddle that's really weird. I do have the uber jar `maven-resolver-ant-tasks-1.5.1-uber.jar` but it doesn't contain `commons-codec`. I've tried 1.5.0 from https://repo1.maven.org/maven2/org/apache/maven/resolver/maven-resolver-ant-tasks/1.5.0/maven-resolver-ant-tasks-1.5.0.jar but it also doesn't appear to!

**Comment by cbfiddle** [comment]
Mac-mini:lib alan$ ll mav*
-rw-r--r--@ 1 alan  staff  4351595 Dec 16 06:55 maven-resolver-ant-tasks-1.5.0-uber.jar
Mac-mini:lib alan$ jar tvf mav* | fgrep /commons-codec/
     0 Sat May 20 13:25:22 PDT 2023 META-INF/maven/commons-codec/
     0 Sat May 20 13:25:22 PDT 2023 META-INF/maven/commons-codec/commons-codec/
 15990 Sat May 20 13:25:22 PDT 2023 META-INF/maven/commons-codec/commons-codec/pom.xml
    62 Sat May 20 13:25:22 PDT 2023 META-INF/maven/commons-codec/commons-codec/pom.properties

**Comment by karlvr** [comment]
Is that listing truncated? It doesn't look like commons-codec code... but either way, the jars I downloaded don't have it. How weird. I'll close this and report back when you release things and see if this situation is any clearer!

**Comment by cbfiddle** [comment]
I see the source of confusion: the codec classes in the maven-resolver-ant-tasks uber JAR are different (internal):

     0 Sun Feb 04 15:10:24 PST 2024 org/apache/maven/resolver/internal/ant/org/apache/commons/codec/
   385 Sun Feb 04 15:10:24 PST 2024 org/apache/maven/resolver/internal/ant/org/apache/commons/codec/BinaryDecoder.class
   385 Sun Feb 04 15:10:24 PST 2024 org/apache/maven/resolver/internal/ant/org/apache/commons/codec/BinaryEncoder.class
   991 Sun Feb 04 15:10:24 PST 2024 org/apache/maven/resolver/internal/ant/org/apache/commons/codec/CharEncoding.class
  1386 Sun Feb 04 15:10:24 PST 2024 org/apache/maven/resolver/internal/ant/org/apache/commons/codec/Charsets.class
  1376 Sun Feb 04 15:10:24 PST 2024 org/apache/maven/resolver/internal/ant/org/apache/commons/codec/CodecPolicy.class

I’m not sure why I don’t run into this problem. When I run ant, it never tries to load commons-codec.

ANT_OPTS="-verbose:class" ant >junk

In fact, it appears to use the internal versions of all the HTTP classes. For example:

[0.541s][info][class,load] org.apache.maven.resolver.internal.ant.org.apache.http.impl.auth.BasicSchemeFactory source: file:/Users/alan/.ant/lib/maven-resolver-ant-tasks-1.5.0-uber.jar

What version of ant are you using?

Releasing VAqua will fix the missing dependency issue, but I don’t see how it will fix the codec problem.

You can work around the dependency issues using a top level build.xml that sets version properties.

For example:

  <typedef resource="org/violetlib/vbuilder/ant/antlib.xml"/>

  <use key="org.violetlib:vappearances" version="4-SNAPSHOT"/>
  <use key="org.violetlib:jnr" version="14-SNAPSHOT"/>
