### ISSUE TITLE
ConcurrentModificationException when calling UIManager.setLookAndFeel()

### ISSUE THREAD

**Issue by yogi1967** [violetlib/vaqua#45]
VAqua look and feel: release 12, build 2023-10-31T23:37:24Z
  using VAquaRendering: release Hybrid master 13x, build 2023-10-22T17:44:22Z

We've started getting this error when calling UIManager.setLookAndFeel()... I'm having trouble pin-point why and when this occurs (not always).... This is the stack trace:

```
20240911-18:10:17.668 Setting look and feel class to org.violetlib.aqua.AquaLookAndFeel
Exception in thread "AWT-EventQueue-0" java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
	at org.violetlib.aqua.AppearanceColorsBuilder.getSystemColors(Unknown Source)
	at org.violetlib.aqua.AppearanceColorsBuilder.<init>(Unknown Source)
	at org.violetlib.aqua.AquaAppearances.getAquaAppearance(Unknown Source)
	at org.violetlib.aqua.AquaAppearances.getOptional(Unknown Source)
	at org.violetlib.aqua.AquaAppearances.get(Unknown Source)
	at org.violetlib.aqua.AppearanceManager.getApplicationAppearance(Unknown Source)
	at org.violetlib.aqua.AppearanceManager.ensureAppearance(Unknown Source)
	at org.violetlib.aqua.AppearanceManager.registerCurrentAppearance(Unknown Source)
	at org.violetlib.aqua.AquaPanelUI.update(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintComponent(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(Unknown Source)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(Unknown Source)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(Unknown Source)
	at java.desktop/java.awt.Container.paint(Unknown Source)
	at java.desktop/java.awt.Window.paint(Unknown Source)
	at java.desktop/java.awt.Container.update(Unknown Source)
	at java.desktop/sun.awt.RepaintArea.updateComponent(Unknown Source)
	at java.desktop/sun.lwawt.LWRepaintArea.updateComponent(Unknown Source)
	at java.desktop/sun.awt.RepaintArea.paint(Unknown Source)
	at java.desktop/sun.lwawt.LWComponentPeer.handleJavaPaintEvent(Unknown Source)
	at java.desktop/sun.lwawt.LWComponentPeer.handleEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```

Java is 21.0.2 (Eclipse Adoptium)..

It's not even showing our calling code in the stack trace..

Thoughts? Thanks

**Comment by yogi1967** [comment]
and then sometimes we are getting the exception:

Exception updating component tree: java.util.ConcurrentModificationException

... when running this code just after..:
    for(Window w : Window.getWindows()) {
      try {
        SwingUtilities.updateComponentTreeUI(w);

So it seems to be 'random' whether we get the first or second error in the same section of code...

**Comment by cbfiddle** [comment]
Make sure you are not doing anything UI-related on the main thread (in your startup code).

If that is not the problem, I would suggest putting a breakpoint on the ConcurrentModificationException constructor.

**Comment by yogi1967** [comment]
Thanks.. Your comments helped 'inspire' a fix - I believe this is resolved.. Sorry to bother you....
